### ISSUE TITLE
RequireJS configuration should not use paths declaration

### ISSUE THREAD

**Issue by mdgeek** [webjars/codemirror#44]
Per CodeMirror's documentation, the RequireJS packages declaration should be used instead of the paths declaration (https://codemirror.net/doc/manual.html#usage):

Do not use RequireJS' paths option to configure the path to CodeMirror, since it will break loading submodules through relative paths. Use the packages configuration option instead.

**Comment by jamesward** [comment]
I'm releasing `5.23.0-1` with this change but we may need to make some changes to https://github.com/webjars/webjars-locator in order for this to work properly.

**Comment by mdgeek** [comment]
Thanks, James.  It looks like the location value needs to be "../" for this to work.  See https://codemirror.net/demo/requirejs.html.

**Comment by jamesward** [comment]
I'm not sure about that since I'm not sure what this value is relative to.  So let's find a way to test this config and then alter if needed.

**Comment by mdgeek** [comment]
Understood.  After spending a couple of hours researching this, I'm still not sure of the answer.  I'll continue looking.  Thanks.

**Comment by mdgeek** [comment]
Not finding any clear documentation on this, I resorted to some brute force testing.  What I found makes sense.  "location" is relative to the base URL and "main" is relative to "location".  This means that for this webjar layout, the location value should be "./", not "../".

**Comment by jamesward** [comment]
I vaguely remember that we do some path munging in `webjars-locator` so it could be that is the place we should do that transformation.  I think we will need to do some testing for this.  What web stack are you using?  I can try to come up with something to test this.

**Comment by mdgeek** [comment]
No web stack at all.  I extracted the webjar to a local folder, created a test HTML page with a script to create an instance of CodeMirror, including one of its addons, set the folder as the baseURL in requireJS, and tried different variations of the package settings.  Attached is the HTML page I used.


[cmtest.html.zip](https://github.com/webjars/codemirror/files/729973/cmtest.html.zip)

**Comment by jamesward** [comment]
The RequireJS config in the `pom.xml` for the WebJar is really intended to be used with `webjars-locator` so using the config outside of that probably won't work correctly.
